# Site settings
title: Bruna Battistini
email: brunabattistini@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I am an architect by training and an artist by instinct.
  I also curate and produce exhibitions. 
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: brunabattistini
github_username:  brunabattistini
instagram_username: brunabattistini

# Build settings
markdown: kramdown


#paginate: 4
#paginate_path: "blog/page:num"

collections:
  projects  :
    output: true
    permalink: /:collection/:path/
    images:


